# generated by datamodel-codegen:
#   filename:  swagger.json
#   timestamp: 2021-03-29T08:55:23+00:00

from __future__ import annotations

from typing import Any, List

from pydantic import BaseModel, Extra

from .io.k8s.apimachinery.pkg.api import resource


class Model(BaseModel):
    __root__: Any


class Extra(BaseModel):
    __root__: List[str]


class VolumeAttributes(BaseModel):
    class Config:
        extra = "allow"

    __root__: str


class BinaryData(BaseModel):
    class Config:
        extra = "allow"

    __root__: str


class Data(BaseModel):
    class Config:
        extra = "allow"

    __root__: str


class Options(BaseModel):
    class Config:
        extra = "allow"

    __root__: str


class NodeSelector(BaseModel):
    class Config:
        extra = "allow"

    __root__: str


class Selector(BaseModel):
    class Config:
        extra = "allow"

    __root__: str


class StringData(BaseModel):
    class Config:
        extra = "allow"

    __root__: str


class Topology(BaseModel):
    class Config:
        extra = "allow"

    __root__: str


class Parameters(BaseModel):
    class Config:
        extra = "allow"

    __root__: str


class AttachmentMetadata(BaseModel):
    class Config:
        extra = "allow"

    __root__: str


class MatchLabels(BaseModel):
    class Config:
        extra = "allow"

    __root__: str


class Annotations(BaseModel):
    class Config:
        extra = "allow"

    __root__: str


class Labels(BaseModel):
    class Config:
        extra = "allow"

    __root__: str


class Default(BaseModel):
    __root__: resource.Quantity


class DefaultRequest(BaseModel):
    __root__: resource.Quantity


class Max(BaseModel):
    __root__: resource.Quantity


class MaxLimitRequestRatio(BaseModel):
    __root__: resource.Quantity


class Min(BaseModel):
    __root__: resource.Quantity


class Allocatable(BaseModel):
    __root__: resource.Quantity


class Capacity(BaseModel):
    __root__: resource.Quantity


class Overhead(BaseModel):
    __root__: resource.Quantity


class Hard(BaseModel):
    __root__: resource.Quantity


class Used(BaseModel):
    __root__: resource.Quantity


class Limits(BaseModel):
    __root__: resource.Quantity


class Requests(BaseModel):
    __root__: resource.Quantity


class PodFixed(BaseModel):
    __root__: resource.Quantity
