version: '3'

services:
  # db:
  #   image: mongodb
  #   env_file:
  #     - .env
  web_app:
    build:
      dockerfile: Dockerfile
      context: .
    image: kubezephyr_backend_image
    env_file:
      - .env
    # depends_on:
    #   - db
    ports:
      - "8000:8000"
