# generated by datamodel-codegen:
#   filename:  swagger.json
#   timestamp: 2021-03-29T08:55:23+00:00

from __future__ import annotations

from pydantic import BaseModel


class RawExtension(BaseModel):
    pass
